# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.3
loader_version=0.16.14
# Mod Properties
mod_version=1.0.0-beta.1+1.20.6
maven_group=top.yangguangmc
archives_base_name=Safeguard
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.100.8+1.20.6
modmenu_version=10.0.0
yacl_version=3.6.6+1.20.6-fabric
